### ISSUE TITLE
Page layout video format learning issues

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/Box-Model#5]
Due to the structure of this section being different I had trouble learning. What normally would have taken me a day, now has taken me two weeks. 

1. **It isn't a readme section, then lab section.** (Ridged structure which I had been used to for the majority of the course, like building blocks building atop one another)
2. **No where in text it said it was supposed to be a codealong - Leading me to watching all the videos then working on the related labs**. ( Most of the videoes and sections before have been codealongs, which I followed the text instead, or reviews of whole concepts or languages. And I learn better visually then listening and in this section, some code ) 
3. **No way to save notes or code.** (Sandbox is the blue button above, so I had to get crafty and save all my code in the codealong creating columns section)

I can't tell if this was purposefully supposed to be a curveball, but by the time I got to the zetsy section, I had no clue what to do and had to rewatch the videos.

If it is a curveball to teach students to expect curveballs, good job.
If its not, I would really mean alot to those who learn more visually than based on listening if you please explicitly write that "**codealong with this video, add to the code provided**", I know it seems obvious to some, but to me I struggled. Thank you.

**Comment by lizbur10** [comment]
Closing - fixed in an earlier update
