### ISSUE TITLE
Missing Links

### ISSUE THREAD

**Issue by Christerlesn** [learn-co-curriculum/Box-Model#7]
All the links that are supposed to appear are non-existent. 
The errors noted are after the following sentences in the README.md:
To get a sense for how these properties work in real time, you can play around with them here: (no link or description)
You can see these principles in action over here: (no link or description)
You can experiment with all of these properties, and see all their pros and cons here: (no link or description).

**Comment by lizbur10** [comment]
Closing - fixed in an earlier update
